---

libs:
  merlion:
    - id: "merlion-Arima"
      model_name: "Arima"
      model_kwargs: {}

    - id: "merlion-Sarima"
      model_name: "Sarima"
      model_kwargs: {}
    
    # - id: "merlion-AutoSarima"
    #   model_name: "AutoSarima"
    #   model_kwargs: {}

    - id: "merlion-ets"
      model_name: "ETS"
      model_kwargs: {}

    - id: "merlion-MSES"
      model_name: "MSES"
      model_kwargs: {}

    # - id: "merlion-prophet"
    #   model_name: "Prophet"
    #   model_kwargs: {}

    # - id: "merlion-AutoProphet"
    #   model_name: "AutoProphet"
    #   model_kwargs: {}

    - id: "merlion-VAR"
      model_name: "VectorAR"
      model_kwargs:
        maxlags: 10

    - id: "merlion-RandomForestForecaster"
      model_name: "RandomForestForecaster"
      model_kwargs:
        maxlags: 10

    - id: "merlion-ExtraTreesForecaster"
      model_name: "ExtraTreesForecaster"
      model_kwargs:
        maxlags: 10        

    - id: "merlion-LGBMForecaster"
      model_name: "LGBMForecaster"
      model_kwargs:
        maxlags: 10

  gluonts:
    - id: "gluonts-SeasonalNaive"
      estimator_class: "gluonts.model.seasonal_naive.SeasonalNaiveEstimator"
      estimator_kwargs: {}
      # no trainer

    - id: "gluonts-NPTS"
      estimator_class: "gluonts.model.npts.NPTSEstimator"
      estimator_kwargs: {}
      # no trainer

    - id: "gluonts-DeepAR"
      estimator_class: "gluonts.model.deepar.DeepAREstimator"
      estimator_kwargs: {}
      trainer_kwargs: {}

    - id: "gluonts-SimpleFeedForward"
      estimator_class: "gluonts.model.simple_feedforward.SimpleFeedForwardEstimator"
      estimator_kwargs: {}
      trainer_kwargs: {}
      
    - id: "gluonts-Transformer"
      estimator_class: "gluonts.model.transformer.TransformerEstimator"
      estimator_kwargs: {}
      trainer_kwargs: {}

  kats:
    - id: "kats-prophet"
      model_class: "kats.models.prophet.ProphetModel"
      params_class: "kats.models.prophet.ProphetParams"
      params_kwargs: {}

    - id: "kats-holtwinters"
      model_class: "kats.models.holtwinters.HoltWintersModel"
      params_class: "kats.models.holtwinters.HoltWintersParams"
      params_kwargs: {}

  neuralprophet:
    - id: "neuralprophet-default"
      model_class: "neuralprophet.NeuralProphet"
      model_kwargs: {}