---

merlion:
  - id: "merlion-Arima1"
    model_name: "Arima"
    model_kwargs:
      order: [30, 0, 10]

gluonts:
  - id: "gluonts-SeasonalNaive"
    estimator_class: "gluonts.model.seasonal_naive.SeasonalNaiveEstimator"
    estimator_kwargs: {}
    # no trainer

